language: node_js
node_js:
  - '6.3.1'
sudo: false
env:
  global:
    - MONGODB_VERSION=3.2.8
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db --quiet &
  - sleep 3
  - npm install
